# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [51]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [52]:
df = pd.read_csv(
   'student-mat.csv',
    sep=','
)

In [53]:
print(df.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [54]:
df = df.loc[:, 'school':'Fjob'].copy()

### Step 5. Create a lambda function that will capitalize strings.

In [55]:
capitalize = lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [56]:
df['Mjob'] = df['Mjob'].apply(capitalize)
df['Fjob'] = df['Fjob'].apply(capitalize)

df

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob
0       GP   F   18       U     GT3       A     4     4   At_home   Teacher
1       GP   F   17       U     GT3       T     1     1   At_home     Other
2       GP   F   15       U     LE3       T     1     1   At_home     Other
3       GP   F   15       U     GT3       T     4     2    Health  Services
4       GP   F   16       U     GT3       T     3     3     Other     Other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  Services  Services
391     MS   M   17       U     LE3       T     3     1  Services  Services
392     MS   M   21       R     GT3       T     1     1     Other     Other
393     MS   M   18       R     LE3       T     3     2  Services     Other
394     MS   M   19       U     LE3       T     1     1     Other   At_home

[395 rows x 10 columns]

### Step 7. Print the last elements of the data set.

In [57]:
df.tail()

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob
390     MS   M   20       U     LE3       A     2     2  Services  Services
391     MS   M   17       U     LE3       T     3     1  Services  Services
392     MS   M   21       R     GT3       T     1     1     Other     Other
393     MS   M   18       R     LE3       T     3     2  Services     Other
394     MS   M   19       U     LE3       T     1     1     Other   At_home

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [58]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv',
    sep=','
)

df = df.loc[:, 'school':'guardian'].copy()

df['Mjob'] = df['Mjob'].apply(capitalize)
df['Fjob'] = df['Fjob'].apply(capitalize)

df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [59]:
def majority(age):
    return age > 17

df['legal_drinker'] = df['age'].apply(majority)

df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,course,other,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother,False
392,MS,M,21,R,GT3,T,1,1,Other,Other,course,other,True
393,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother,True
394,MS,M,19,U,LE3,T,1,1,Other,At_home,course,father,True

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [60]:
df = df.apply(lambda x: x * 10 if x.dtype != 'object' else x)

df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,180,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,AAAAAAAAAA,40,40,At_homeAt_homeAt_homeAt_homeAt_homeAt_homeAt_h...,TeacherTeacherTeacherTeacherTeacherTeacherTeac...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,10
1,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,170,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,10,10,At_homeAt_homeAt_homeAt_homeAt_homeAt_homeAt_h...,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,coursecoursecoursecoursecoursecoursecoursecour...,fatherfatherfatherfatherfatherfatherfatherfath...,0
2,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,150,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,10,10,At_homeAt_homeAt_homeAt_homeAt_homeAt_homeAt_h...,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,otherotherotherotherotherotherotherotherothero...,mothermothermothermothermothermothermothermoth...,0
3,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,150,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,40,20,HealthHealthHealthHealthHealthHealthHealthHeal...,ServicesServicesServicesServicesServicesServic...,homehomehomehomehomehomehomehomehomehome,mothermothermothermothermothermothermothermoth...,0
4,GPGPGPGPGPGPGPGPGPGP,FFFFFFFFFF,160,UUUUUUUUUU,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,30,30,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,homehomehomehomehomehomehomehomehomehome,fatherfatherfatherfatherfatherfatherfatherfath...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,200,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,AAAAAAAAAA,20,20,ServicesServicesServicesServicesServicesServic...,ServicesServicesServicesServicesServicesServic...,coursecoursecoursecoursecoursecoursecoursecour...,otherotherotherotherotherotherotherotherothero...,10
391,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,170,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,30,10,ServicesServicesServicesServicesServicesServic...,ServicesServicesServicesServicesServicesServic...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,0
392,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,210,RRRRRRRRRR,GT3GT3GT3GT3GT3GT3GT3GT3GT3GT3,TTTTTTTTTT,10,10,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,coursecoursecoursecoursecoursecoursecoursecour...,otherotherotherotherotherotherotherotherothero...,10
393,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,180,RRRRRRRRRR,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,30,20,ServicesServicesServicesServicesServicesServic...,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,coursecoursecoursecoursecoursecoursecoursecour...,mothermothermothermothermothermothermothermoth...,10
394,MSMSMSMSMSMSMSMSMSMS,MMMMMMMMMM,190,UUUUUUUUUU,LE3LE3LE3LE3LE3LE3LE3LE3LE3LE3,TTTTTTTTTT,10,10,OtherOtherOtherOtherOtherOtherOtherOtherOtherO...,At_homeAt_homeAt_homeAt_homeAt_homeAt_homeAt_h...,coursecoursecoursecoursecoursecoursecoursecour...,fatherfatherfatherfatherfatherfatherfatherfath...,10